# 2) Корреляция признаков с таргетом (Pearson, train)
c_with_y = cmat[y_col].drop(labels=[y_col]).sort_values(key=abs, ascending=False)
plt.figure(figsize=(9, 7))
c_with_y.plot(kind="barh", color=["C3" if v < 0 else "C0" for v in c_with_y])
plt.title("Корреляция признаков с целью цель_24ч (Pearson)")
plt.axvline(0, color="k", lw=0.8)
plt.tight_layout()
plt.show()
print(c_with_y.round(3).to_string())